#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" |sudo tee /var/www/html/index.html
sudo service nginx start
